const trending = [
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABVoUb_b5kh_yNaUP7KrJ0SixY7wboYlzRCUdKII9nZ7oSYyAYPShAtL0spCP-KQXAvTngiRZqy7Kqk0egCiKWfpaIrc4S9LT9gPeEcdFpM3H9CuyLTNXW-nev14zWvjHmDzP.jpg?r=cac',
        alt: 'Midnight Diner: Tokyo Stories',
        maturityRating: '13+',
        seasonLength: '3 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Sentimental',
        genresTwo: 'Understated',
        genresThree: 'Drama',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABdgTW1x53wm762Jk0TtkGTOhi4boVORa2qQg-GvNlkbeu_Cg5xSrsHN0aE-03y_bkmQwnxnvFwlsuDbabRnWUgAk0KkyOLoE_f8.webp?r=a65',
        alt: 'Lost',
        maturityRating: '16+',
        seasonLength: '6 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Emotional',
        genresTwo: 'Exciting',
        genresThree: 'Adventure',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABX2PfVhkMZlw8pvS-LUgyk8GpmKv48_tRsA6rgSV8ppFvijet4MWICbJW-3I369_O1kaxVEl0aCY957Ma9wpLzqm37MYsN5AQT8.webp?r=cfb',
        alt: 'Adventure Time',
        maturityRating: '10+',
        seasonLength: '4 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Clever',
        genresTwo: 'Quirky',
        genresThree: 'Kids',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABQOGyZS-6Oi0JRI__YiHy2cDTTktNLJ4hL0_EiSiKvh0mQPhpPNqnUo6a8SNzwFRnZHgn_4D19cLS5DhSqZnkxQ5AjI4M8elvdM.webp?r=f29',
        alt: 'Avatar',
        maturityRating: '10+',
        seasonLength: '3 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Clever',
        genresTwo: 'Rousing',
        genresThree: 'Imaginative',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABQ7JWJm3TNKnhWZwFkZg5MwlCJoWXNedXpecv1qdsym10FF3x7rMPxOqcvFeMIe4m-e0Lpz0M_78zcFfp2NX4JD_E6ad_SF6KLw.webp?r=82d',
        alt: 'The Office',
        maturityRating: '13+',
        seasonLength: '9 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Witty',
        genresTwo: 'Irreverent',
        genresThree: 'Sitcoms',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABeMSDWszjl16jq7qFSWk8uIzw0T53Vaag65yKbuXMN-etObAVJPWHbdvx8oe0Kv362vFmLe7KX0iL4Vb3eAPAUTit1ueVdBY3ZILFKNIf4RAKTLx8jgRNHokWBKgiIiTv1hF.jpg?r=696',
        alt: 'Better Call Saul',
        maturityRating: '16+',
        seasonLength: '6 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Offbeat',
        genresTwo: 'Gritty',
        genresThree: 'TV Dramas',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABfw8DaShSWvrVPjNRyQZMNXg4_CVerMtfpZHCUspl1T5KTO-rVUxu_rQVr6W_Y7BDIuWljsPzXXZqz7IeC-XwCFHu3bKN6ZUtp8.webp?r=af6',
        alt: 'Old Enough!',
        maturityRating: '7+',
        seasonLength: '2 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Feel-Good',
        genresTwo: 'Family Time TV',
        genresThree: 'Japanese',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABfJTX7eAb5oFLjM9kuUUEskoHC8dP-kQOLCu1Iq85xFEu_AehlXpQbEhtb5N9KFE1bW7HzNDCS3Z-h0Qm6RtVuWWd-gUqenlYfl4bP5UZD0rD39m1U_Y-2GqbKFmNZfw5BoG.jpg?r=72f',
        alt: "JoJo's Bizarre Adventure",
        maturityRating: '16+',
        seasonLength: '5 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Exciting',
        genresTwo: 'Shounen Anime',
        genresThree: 'Action Anime',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABWc2d5lqwRHzflRJSjpRzQCrHOSqLYzJ2Ka519EwDMpWe1oaVaY__i_Onhz-z412wtPJRnPF38cf0O7KZhVWmmpJ1WuttbUWReOJ-6KUhfK70FyCUKxFFh_5-2SIZ-Cykr9l.jpg?r=1f3',
        alt: 'Our Universe',
        maturityRating: '7+',
        seasonLength: 'Limited Series',
        playerFeatureBadge: 'HD',
        genresOne: 'Relaxing',
        genresTwo: 'Cerebral',
        genresThree: 'Family Time TV',
    },
];
