const watchAgain = [
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABZGjw3eiZBPX3PClNvoEW5Qvyuvg0yJ8WC1R00mYeeSrP_Wq1ObH3c9832gtAV4HbsH8Rktv0fA73AVOyQmTY6Gdm-AsJDqh7nMqvG2WABBh9agqH7mOoIgrmBD-pkWelBnN.jpg?r=962',
        alt: 'Live to 100: Secrets of the Blue Zones',
        maturityRating: '10+',
        seasonLength: 'Limited Series',
        playerFeatureBadge: 'HD',
        genresOne: 'Inspiring',
        genresTwo: 'Heartfelt',
        genresThree: 'Food &amp; Travel TV',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABWFivdM01yCAxgcgMEukBOTzCCtQ02-SC9wLTAIqJOiJPOxsiuVnNokzw6ERYSLQ1s-NKqFXxyuU-WoIYQhG6w2Y_nuQ_d_A55n02xzfSVm5DJhN93-B5yg2RQEIaDp9cuqn.jpg?r=c49',
        alt: 'Unknown: Cosmic Time Machine',
        maturityRating: 'ALL',
        seasonLength: '1h 4m',
        playerFeatureBadge: 'HD',
        genresOne: 'Investigative',
        genresTwo: 'Documentray Films',
        genresThree: 'Science &amp; Nature Docs',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABdooux6TG8BM4ZrfzBAdgS6Uu7U3WZQt1Yql4STgFuz5q-yxiT_zasNUA1yzVy-40r57TGHRtSnrAWVEXJKzWKwyS7tKyPYI9aKDPcDFAZt1eGAeTY-WZdxiL3rrhjPFIKwl.jpg?r=ea6',
        alt: 'The Way of the Househusband',
        maturityRating: '13+',
        seasonLength: '2 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Deadpan',
        genresTwo: 'Absurd',
        genresThree: 'Quirky',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABScU9si84a7dUBrLejJ56w8wBjDyedjmr2aoZwyuhkTFVioYvvC4B_3CDzXHO8bRil3zTFfoZe8OzJcU9RdIKTDdek0WWHhNzBO7k2ekpqmbUFXHADBlvGyuoj6B-EH0ORzG.jpg?r=112',
        alt: 'Mindhunter',
        maturityRating: '16+',
        seasonLength: '2 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Chilling',
        genresTwo: 'Psychological',
        genresThree: 'TV Dramas',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABf2hzn0yZQQYIIfUgIbBPaN46wFbffcX1ZOhtq0q3e0-N_gLGH8Lx3s5DOmYls4PNHAKA1XP9BuwUIXOMrPyciiCrBwj3olikoI.webp?r=a41',
        alt: 'Interstellar',
        maturityRating: '13+',
        seasonLength: '2h 49m',
        playerFeatureBadge: 'HD',
        genresOne: 'Mind-Bending',
        genresTwo: 'Cerebral',
        genresThree: 'Sci-Fi Movies',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABa5BCf6HoCBQCEQW5JNP301dwSPyJPEXbFicrHodTtnqA1AtzHfQyEfkHWQurDLPdc9Eq4LszcOs9gzzykJ3FvNwjhX2B7KLteY.webp?r=edf',
        alt: 'Rick and Morty',
        maturityRating: '16+',
        seasonLength: '7 Seasons',
        playerFeatureBadge: 'HD',
        genresOne: 'Absurd',
        genresTwo: 'Violent',
        genresThree: 'Quirky',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABTzIxLs3nhQuvkJ10Bwvf9HcidFA1o9QcLrqrtqQ1kJsf5AsqxGJfrk1rLNymppxwozwev2aLGoYZyEKS3XpmOoZAv5oKcKSaHQ.webp?r=2b9',
        alt: 'Cowboy Bebop',
        maturityRating: '16+',
        seasonLength: '26 Episodes',
        playerFeatureBadge: 'HD',
        genresOne: 'Offbeat',
        genresTwo: 'Witty',
        genresThree: 'Action Anime',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABaE6ehOFF1Lgn84imWJtALvvF7ygfKVLE5Z2vn6Fq0_r16_PFpQgC62Vvxnx1g9GZ__OFtGlNLZsu4VbVmNfWRnbte2UE2GVMFV3zm0fZVvQuvD7RWr2ajUIQqmK5cPnE2NC.jpg?r=2b0',
        alt: 'The Wonderful Story of Henry Sugar',
        maturityRating: 'ALL',
        seasonLength: '39m',
        playerFeatureBadge: 'HD',
        genresOne: 'Imaginative',
        genresTwo: 'Drama Movies',
        genresThree: 'Movies Based on Books',
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABfjGlvVeALl76ib7TIZy_-U7wyBKIldVloODtBfoHdKNe9Stp2FWnyciNYHa3XUuyZF_NN-JILrfNbSDya7qk_emCvgj0-OJlps.webp?r=b00',
        alt: 'Akira',
        maturityRating: '16+',
        seasonLength: '2h 4m',
        playerFeatureBadge: 'HD',
        genresOne: 'Exciting',
        genresTwo: 'Action Anime',
        genresThree: 'Sci-Fi Movies',
    },
];
